Fetch API and Add navigation
awesome-academy/ios_open_nguyen_hoang_linh_gcd_coredata_homework pull request #4
Opened 2023-08-30 03:14 UTC by hlinh88

## [Task] Fetch API and Add navigation

### [Redmine link]

#### Screenshots (nếu có)

https://github.com/awesome-academy/ios_open_nguyen_hoang_linh_gcd_coredata_homework/assets/73870812/1a3fdcbd-93c3-4616-86eb-59f6c4109381

2023-08-30 03:17 UTC, TuanKieuDev commented on UserList/UserList/Controller/HomeViewController.swift
> +    private func customizeView(){
```suggestion
    private func customizeView() {
```
Tương tự với các phần còn lại

2023-08-30 03:20 UTC, TuanKieuDev approved these changes

2023-08-30 03:23 UTC, tunghs-1253 commented on UserList/UserList/Controller/HomeViewController.swift
> +        URLSession.shared.dataTask(with: url) {(data, response, error) in
```suggestion
        URLSession.shared.dataTask(with: url) { (data, response, error) in
```

2023-08-30 03:23 UTC, tunghs-1253 commented on UserList/UserList/Controller/HomeViewController.swift
> +        let url = URL(string: apiEndpoint)!
Không force unwrap

2023-08-30 03:24 UTC, tunghs-1253 commented on UserList/UserList/Controller/HomeViewController.swift
> +        let apiEndpoint = "https://api.github.com/search/users?q=abc"
URL tách riêng, Endpoint tách riêng ra file enum em

2023-08-30 04:26 UTC, 2fng commented on UserList/UserList/Controller/FavouriteViewController.swift
> +//        initFavouriteList()
Không đẩy comment lên PR

2023-08-30 04:26 UTC, 2fng commented on UserList/UserList/Controller/FavouriteViewController.swift
> +//    }
Tương tự như trên

2023-08-30 04:26 UTC, 2fng commented on UserList/UserList/Controller/HomeViewController.swift
> +            }.resume()
Retain cycle

2023-08-30 04:26 UTC, 2fng commented on UserList/UserList/Controller/HomeViewController.swift
> +        if let url = URL(string: Endpoint.api.rawValue){
```suggestion
        if let url = URL(string: Endpoint.api.rawValue) {
```

2023-08-30 06:13 UTC, 2fng requested changes

2023-08-30 06:13 UTC, 2fng commented on UserList/UserList/Controller/HomeViewController.swift
> +        }
```suggestion
            self.users.append(User(image: item.avatar_url,
             name: item.login,
              link: item.html_url,
              profileLink: item.url))
        }
```

2023-08-30 06:13 UTC, 2fng commented on UserList/UserList/Controller/ProfileViewController.swift
> +    @IBOutlet private weak var userBio: UILabel!
```suggestion
    @IBOutlet private weak var userImageView: UIImageView!
    @IBOutlet private weak var userNameLabel: UILabel!
    @IBOutlet private weak var userBioLabel: UILabel!
```

2023-08-30 06:13 UTC, 2fng commented on UserList/UserList/Controller/ProfileViewController.swift
> +    }
Tách riêng ra và áp dụng Repository Design Pattern em nhé

2023-08-30 06:13 UTC, 2fng commented on UserList/UserList/Controller/ProfileViewController.swift
> +                            }
Chỗ này retain cycle

2023-08-30 06:13 UTC, 2fng commented on UserList/UserList/Extension/ImageViewExtension.swift
> +    }
Tương tự như trên

2023-08-30 06:13 UTC, 2fng commented on UserList/UserList/View/UserTableViewCell.swift
> +    @IBAction func userButtonTapped(_ sender: UIButton) {
private

2023-08-31 02:47 UTC, tunghs-1253 commented on UserList/UserList/Controller/FavouriteViewController.swift
> +    @IBAction func backButtonTapped(_ sender: UIButton) {
private

2023-08-31 02:48 UTC, tunghs-1253 commented on UserList/UserList/Controller/HomeViewController.swift
> +                self.userTableView.reloadData()
Sao đoạn này phải đổi sang main queue em nhỉ

2023-08-31 02:49 UTC, tunghs-1253 commented on UserList/UserList/Controller/HomeViewController.swift
> +extension HomeViewController: UITableViewDelegate, UITableViewDataSource, UserTableViewCellDelegate, UISearchBarDelegate {
Tách riêng Delegate, DataSource,... ra em. Mà 2 cái sau là cái gì thế

2023-08-31 02:49 UTC, tunghs-1253 commented on UserList/UserList/Controller/HomeViewController.swift
> +    func userButtonTapped(sender: UIButton) {
private

2023-08-31 02:49 UTC, tunghs-1253 commented on UserList/UserList/Controller/HomeViewController.swift
> +    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
private

2023-08-31 02:51 UTC, tunghs-1253 commented on UserList/UserList/Controller/ProfileViewController.swift
> +    private func passDataToView(image: String, name: String, bio: String?, follower: Int?, following: Int?, repo: Int?) {
Xuống dòng ở từng param trông cho đỡ rối em

2023-08-31 02:51 UTC, tunghs-1253 commented on UserList/UserList/Controller/ProfileViewController.swift
> +    @IBAction func backButtonTapped(_ sender: UIButton) {
private

2023-08-31 03:41 UTC, hlinh88 commented on UserList/UserList/Controller/HomeViewController.swift
> +extension HomeViewController: UITableViewDelegate, UITableViewDataSource, UserTableViewCellDelegate, UISearchBarDelegate {
2 cái sau UserTableViewCellDelegate là để em lấy đươc index của cell còn UISearchBarDelegate là để em viết function cho searchbar anh ạ

2023-08-31 03:42 UTC, hlinh88 commented on UserList/UserList/Controller/HomeViewController.swift
> +    func userButtonTapped(sender: UIButton) {
func userButton này là em viết cho cái UserTableViewCellDelegate để pass data (do cái view em chọn là button chứ không phải rowView của tableView) nên em không để private

2023-08-31 03:44 UTC, hlinh88 commented on UserList/UserList/Controller/HomeViewController.swift
> +    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
func userButton này là em viết cho cái UISearchBarDelegate để handle search button nên em không để private a

2023-08-31 03:45 UTC, hlinh88 commented on UserList/UserList/Controller/HomeViewController.swift
> +                self.userTableView.reloadData()
tại nếu em ko cho vào main queue thì cái users list của em nó không update vì phải chờ API fetch xong anh ạ

2023-08-31 03:58 UTC, tunghs-1253 commented on UserList/UserList/Repository/apiRepository.swift
> +class apiRepository: APIRepository {
Class đặt tên sai convention, chưa private

2023-08-31 03:58 UTC, tunghs-1253 commented on UserList/UserList/Repository/apiRepository.swift
> +class apiRepository: APIRepository {
Ngoài ra tạo singleton cho repo em nhé

2023-08-31 04:21 UTC, tunghs-1253 commented on UserList/UserList/Repository/ApiRepository.swift
> +final class ApiRepository: APIRepository {
```suggestion
final class APIRepository: APIRepository {
```

2023-08-31 04:21 UTC, tunghs-1253 commented on UserList/UserList/Repository/ApiRepository.swift
> +protocol APIRepository {
```suggestion
protocol APIRepositoryType {
```

2023-08-31 06:06 UTC, merged